name: "omg.lol GitHub status sync"
description: "Syncs your omg.lol and GitHub user profile statuses"
author: "Lucas Melin"
branding:
  icon: "refresh-ccw"
  color: "purple"
inputs:
  omg_lol_user: # change this
    required: true
    description: "omg.lol username"
  github_token:
    required: true
    description: "GitHub token with user scope"
outputs:
  emoji:
    description: "The emoji used in the status"
  message:
    description: "The status message text"
runs:
  using: "node20"
  main: "dist/index.js"
